# Generated by Django 2.2 on 2020-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('client', 'Физическое лицо'), ('company', 'Юридическое лицо'), ('seller', 'Продавец'), ('admin', 'Администратор')], max_length=20, verbose_name='Тип'),
        ),
    ]
