# Generated by Django 2.2 on 2020-05-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_product', to='webapp.Product', verbose_name='Карусель'),
        ),
    ]
