# Generated by Django 2.2 on 2020-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20200528_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Цена доставки')),
                ('free_from', models.IntegerField(verbose_name='Бесплатная доставка при сумме заказа от')),
            ],
        ),
    ]
