# Generated by Django 2.2 on 2020-06-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_deliverycost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycost',
            options={'verbose_name': 'Стоимость доставки', 'verbose_name_plural': 'Стоимость доставки'},
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='cost',
            field=models.IntegerField(verbose_name='Стоимость доставки'),
        ),
    ]
