# Generated by Django 2.2 on 2020-06-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
