# Generated by Django 2.2 on 2020-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_deliverycost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
