# Generated by Django 2.2 on 2020-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20200612_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('none', 'нет'), ('white', 'Белый'), ('green', 'Зеленый'), ('grey', 'Серый'), ('blue', 'Синий'), ('red', 'Красный'), ('yellow', 'Желтый'), ('black', 'Черный'), ('orange', 'Оранжевый'), ('brown', 'Коричневый'), ('beige', 'Бежевый'), ('pink', 'Розовый'), ('purple', 'Фиолетовый'), ('darkblue', 'Темно-синий'), ('darkgreen', 'Темно-зеленый')], default='none', max_length=20, null=True, verbose_name='Цвет'),
        ),
    ]
