# Generated by Django 2.2 on 2020-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20200617_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main_carousel_images', verbose_name='Картинка карусели')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
        ),
    ]
