# Generated by Django 2.2 on 2020-06-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_deliveryaddress_user'),
        ('webapp', '0026_maincarousel'),
    ]

    operations = [
    ]
