# Generated by Django 2.2 on 2020-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_product_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincarousel',
            options={'verbose_name': 'Главная карусель', 'verbose_name_plural': 'Главная карусель'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='maincarousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_carousel_images', verbose_name='Картинка карусели (фон)'),
        ),
        migrations.AlterField(
            model_name='maincarousel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main_carousel_images', verbose_name='Картинка'),
        ),
    ]
