# Generated by Django 2.2 on 2020-07-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_productincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(choices=[('Бишкек', 'Бишкек')], default='Бишкек', max_length=20, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='productincategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_category', to='webapp.Product', verbose_name='Рекоммендуемы товар в категории'),
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speсifications', to='webapp.Product')),
            ],
            options={
                'verbose_name': 'Характеристи',
                'verbose_name_plural': 'Характеристика',
            },
        ),
    ]
