# Generated by Django 2.2 on 2020-07-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20200704_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название характеристики'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='webapp.Product'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Значение характеристики'),
        ),
    ]
