# Generated by Django 2.2 on 2020-07-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20200712_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalpayment',
            name='txn_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TXN_ID'),
        ),
    ]
