# Generated by Django 2.2 on 2020-07-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_terminalpayment_txn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=9999, max_digits=9),
            preserve_default=False,
        ),
    ]
