# Generated by Django 2.2 on 2020-07-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_auto_20200713_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='free_from',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Бесплатная доставка при сумме заказа от'),
        ),
    ]
