# Generated by Django 2.2 on 2020-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_auto_20200731_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Дилерская Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='trade_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая Цена'),
        ),
    ]
