# Generated by Django 2.2 on 2020-08-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_auto_20200807_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='Белый', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colors', to='webapp.Color', verbose_name='Цвет'),
        ),
    ]
