# Generated by Django 2.2 on 2020-08-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_auto_20200808_1917'),
        ('webapp', '0055_auto_20200807_1005'),
    ]

    operations = [
    ]
