# Generated by Django 2.2 on 2020-08-18 20:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0056_merge_20200809_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='white', max_length=18, verbose_name='Цвет'),
        ),
    ]
